name = "rss-doge"
account_id = "192f419a98de6d7213ce83e0fcf04e51"
workers_dev = true
main = "src/index.ts"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-09-23"

vars = { ENVIRONMENT = "production" }

kv_namespaces = [
    { binding = "RSSDOGE", id = "76fc30a6d6d148d5be413382baa29228", preview_id = "73297cedbf154a03972f47fc4baabd6a" }
]

[triggers]
crons = ["0,30 9-18 * * mon-fri"]
