export default (env) => {
  return {
    production: {
      authentication: true,
      baseURL: "https://rss-doge.melkikh.workers.dev/",
      telegramToken: env.TELEGRAM_TOKEN,
      telegramChatID: "@secpaperboy",
      sentry_dsn: env.SENTRY_DSN,
      updateCount: 10,
      feeds: {
        netsec: "https://reddit.com/r/netsec.rss",
        opennet: "https://www.opennet.ru/opennews/opennews_sec.rss",
        meta_engineering: "https://engineering.fb.com/feed/",
        google_online_security: "http://feeds.feedburner.com/GoogleOnlineSecurityBlog",
        google_project_zero: "https://googleprojectzero.blogspot.com/feeds/posts/default",
        rapid7: "https://blog.rapid7.com/rss/",
        tavis_ormandy: "http://blog.cmpxchg8b.com/feeds/posts/default",
        tailscale: "https://tailscale.com/blog/index.xml",
        datadog_security: "https://securitylabs.datadoghq.com/rss/feed.xml",
        patryk_kosieradzki: "https://patrykkosieradzki.medium.com/feed",
        doyensec: "https://blog.doyensec.com/atom.xml",
        trailofbits: "https://blog.trailofbits.com/feed/",
        miro_engineering: "https://medium.com/feed/miro-engineering",
        raesene: "https://raesene.github.io/feed.xml",
        teleport: "https://goteleport.com/blog/rss.xml",
        cloudflare_security: "https://blog.cloudflare.com/tag/security/rss",
        cloudflare_research: "https://blog.cloudflare.com/tag/research/rss",
        ksoc: "https://ksoc.com/blog/rss.xml",
        okta_security: "https://sec.okta.com/rss.xml",
        unskilled: "https://unskilled.blog/index.xml",
        rami_mac: "https://ramimac.me/feed.xml",
        kanenarraway: "https://kanenarraway.com/index.xml",
      },
    },
    development: {
      authentication: false,
      baseURL: "http://127.0.0.1:3000/",
      telegramToken: env.TELEGRAM_TOKEN,
      telegramChatID: "51818321",
      sentry_dsn: env.SENTRY_DSN,
      updateCount: 10,
      feeds: {
        cloudflare_workers: "https://blog.cloudflare.com/tag/workers/rss",
      },
    },
  }[env.ENVIRONMENT];
};
